class BebrasBiro {
  String bebrasBiroUniv;
  String valueDropdown;
  bool isActive;

  BebrasBiro({
    required this.bebrasBiroUniv,
    required this.valueDropdown,
    this.isActive = true,
  });

  String userAsString() {
    return bebrasBiroUniv;
  }
}

List<String> bebrasBiroList = [
  'Institut Teknologi Bandung',
  'Institut Pertanian Bogor',
  'Universitas Indonesia',
  'Institut Teknologi Sepuluh November',
  'Universitas Kristen Maranatha',
  'Universitas Atmajaya Yogyakarta',
  'Universitas Diponegoro',
  'Universitas Islam Indonesia',
  'Universitas Jendral Soedirman',
  'Universitas Jember',
  'Universitas Sriwijaya',
  'Institut Teknologi Del',
  'Sekolah Tinggi Teknologi Garut',
  'Universitas Mulawarman',
  'Unversitas Udayana',
  'Universitas Negeri Malang',
  'Universitas Dian Nuswantoro',
  'Politeknik Caltex Riau',
  'Universitas Katolik Parahyangan',
  'Institut Teknologi Sumatera',
  'Universitas Lambung Mangkurat',
  'Universitas Tanjungpura',
  'Universitas Sumatera Utara',
  'Universitas Pembangunan Jaya',
  'Universitas Kristen Satya Wacana',
  'Universitas Maritim Raja Ali Haji',
  'Universitas Paramadina',
  'Universitas Katolik Widya Mandira',
  'Politeknik Negeri Batam',
  'Politeknik Negeri Malang',
  'Universitas Katolik Soegijapranata',
  'Universitas Muhammadiyah Surakarta',
  'Politeknik Negeri Jakarta',
  'Universitas Gadjah Mada',
  'Universitas Negeri Yogyakarta',
  'Politeknik Negeri Bandung',
  'Universitas Hasanudin',
  'UIN Alauddin Makassar',
  'Universitas Pasundan',
  'Universitas Telkom',
  'Universitas Sanata Dharma',
  'Universitas Andalas',
  'Universitas Islam Nusantara',
  'Universitas Sains Al-Qur’an Wonosobo',
  'Universitas Bina Nusantara',
  'Universitas Komputer Indonesia',
  'Universitas Singaperbangsa Karawang',
  'Universitas Pendidikan Indonesia Kampus Purwakarta',
  'Universitas President',
  'STIKOM PGRI Banyuwangi',
  'Universitas Bumigora',
  'Universitas Pendidikan Indonesia',
  'Universitas Padjadjaran',
  'Universitas Katolik De La Salle Manado',
  'Universitas Ahmad Dahlan',
  'Universitas Negeri Makassar',
  'Universitas Pendidikan Muhammadiyah Sorong',
  'Universitas Al-Azhar Indonesia',
  'Politeknik Negeri Indramayu',
  'Universitas Nahdlatul Ulama Sunan Giri Bojonegoro',
  'Institut Bisnis dan Informatika Kwik Kian Gie',
  'Universitas Internasional Semen Indonesia',
  'Politeknik Negeri Madiun',
  'Universitas Kristen Petra',
  'Universitas Muhammadiyah Magelang',
  'Universitas Surabaya',
  'Universitas Katolik Indonesia Atma Jaya',
  'Universitas Ciputra Surabaya',
  'Universitas Katolik Widya Mandala Surabaya',
  'Universitas Kristen Duta Wacana',
  'Politeknik Manufaktur Negeri Bangka Belitung',
  'Universitas Kristen Krida Wacana',
  'Institut Agama Islam Negeri Salatiga',
  'Universitas Muhammadiyah Purworejo',
  'Institut Teknologi dan Bisnis Kalbis',
  'Universitas Mercu Buana Jakarta',
  'UPN “Veteran” Jakarta',
  'Universitas Pertamina',
  'Universitas Dr. Soetomo',
  'Universitas Bakrie',
  'Universitas Bengkulu',
  'UIN Walisongo Semarang',
  'Universitas Islam Sultan Agung Semarang',
  'UIN Imam Bonjol Padang',
  'Institut Pesantren Mathali’ul Falah Pati',
  'UIN Sunan Gunung Djati Bandung',
  'IAIN Pekalongan',
  'UIN Sultan Aji Muhammad Idris Samarinda',
  'Politeknik Jambi',
  'Universitas Trisakti',
  'Biro Institut Teknologi dan Bisnis Yadika Pasuruan',
  'Biro Universitas Widyagama Malang',
];
