class BebrasBiro {
  String bebrasBiroUniv;
  String valueDropdown;
  bool isActive;

  BebrasBiro({
    required this.bebrasBiroUniv,
    required this.valueDropdown,
    this.isActive = true,
  });

  String userAsString() {
    return this.bebrasBiroUniv;
  }
}

List<BebrasBiro> bebrasBiroList = [
  BebrasBiro(bebrasBiroUniv: "Institut Teknologi Bandung", valueDropdown: "institut_teknologi_bandung", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Institut Pertanian Bogor", valueDropdown: "institut_pertanian_bogor", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Indonesia", valueDropdown: "universitas_indonesia", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Institut Teknologi Sepuluh November", valueDropdown: "institut_teknologi_sepuluh_november", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Kristen Maranatha", valueDropdown: "universitas_kristen_maranatha", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Atmajaya Yogyakarta", valueDropdown: "universitas_atmajaya_yogyakarta", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Diponegoro", valueDropdown: "universitas_diponegoro", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Islam Indonesia", valueDropdown: "universitas_islam_indonesia", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Jendral Soedirman", valueDropdown: "universitas_jendral_soedirman", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Jember", valueDropdown: "universitas_jember", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Sriwijaya", valueDropdown: "universitas_sriwijaya", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Institut Teknologi Del", valueDropdown: "institut_teknologi_del", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Sekolah Tinggi Teknologi Garut", valueDropdown: "sekolah_tinggi_teknologi_garut", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Mulawarman", valueDropdown: "universitas_mulawarman", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Unversitas Udayana", valueDropdown: "unversitas_udayana", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Negeri Malang", valueDropdown: "universitas_negeri_malang", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Dian Nuswantoro", valueDropdown: "universitas_dian_nuswantoro", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Caltex Riau", valueDropdown: "politeknik_caltex_riau", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Katolik Parahyangan", valueDropdown: "universitas_katolik_parahyangan", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Institut Teknologi Sumatera", valueDropdown: "institut_teknologi_sumatera", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Lambung Mangkurat", valueDropdown: "universitas_lambung_mangkurat", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Tanjungpura", valueDropdown: "universitas_tanjungpura", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Sumatera Utara", valueDropdown: "universitas_sumatera_utara", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Pembangunan Jaya", valueDropdown: "universitas_pembangunan_jaya", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Kristen Satya Wacana", valueDropdown: "universitas_kristen_satya_wacana", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Maritim Raja Ali Haji", valueDropdown: "universitas_maritim_raja_ali_haji", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Paramadina", valueDropdown: "universitas_paramadina", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Katolik Widya Mandira", valueDropdown: "universitas_katolik_widya_mandira", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Negeri Batam", valueDropdown: "politeknik_negeri_batam", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Negeri Malang", valueDropdown: "politeknik_negeri_malang", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Katolik Soegijapranata", valueDropdown: "universitas_katolik_soegijapranata", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Muhammadiyah Surakarta", valueDropdown: "universitas_muhammadiyah_surakarta", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Negeri Jakarta", valueDropdown: "politeknik_negeri_jakarta", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Gadjah Mada", valueDropdown: "universitas_gadjah_mada", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Negeri Yogyakarta", valueDropdown: "universitas_negeri_yogyakarta", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Negeri Bandung", valueDropdown: "politeknik_negeri_bandung", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Hasanudin", valueDropdown: "universitas_hasanudin", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "UIN Alauddin Makassar", valueDropdown: "uin_alauddin_makassar", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Pasundan", valueDropdown: "universitas_pasundan", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Telkom", valueDropdown: "universitas_telkom", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Sanata Dharma", valueDropdown: "universitas_sanata_dharma", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Andalas", valueDropdown: "universitas_andalas", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Islam Nusantara", valueDropdown: "universitas_islam_nusantara", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Sains Al-Qur’an Wonosobo", valueDropdown: "universitas_sains_al_qur_an_wonosobo", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Bina Nusantara", valueDropdown: "universitas_bina_nusantara", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Komputer Indonesia", valueDropdown: "universitas_komputer_indonesia", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Singaperbangsa Karawang", valueDropdown: "universitas_singaperbangsa_karawang", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Pendidikan Indonesia Kampus Purwakarta", valueDropdown: "universitas_pendidikan_indonesia_kampus_purwakarta", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas President", valueDropdown: "universitas_president", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "STIKOM PGRI Banyuwangi", valueDropdown: "stikom_pgri_banyuwangi", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Bumigora", valueDropdown: "universitas_bumigora", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Pendidikan Indonesia", valueDropdown: "universitas_pendidikan_indonesia", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Padjadjaran", valueDropdown: "universitas_padjadjaran", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Katolik De La Salle Manado", valueDropdown: "universitas_katolik_de_la_salle_manado", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Ahmad Dahlan", valueDropdown: "universitas_ahmad_dahlan", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Negeri Makassar", valueDropdown: "universitas_negeri_makassar", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Pendidikan Muhammadiyah Sorong", valueDropdown: "universitas_pendidikan_muhammadiyah_sorong", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Al-Azhar Indonesia", valueDropdown: "universitas_al_azhar_indonesia", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Negeri Indramayu", valueDropdown: "politeknik_negeri_indramayu", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Nahdlatul Ulama Sunan Giri Bojonegoro", valueDropdown: "universitas_nahdlatul_ulama_sunan_giri_bojonegoro", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Institut Bisnis dan Informatika Kwik Kian Gie", valueDropdown: "institut_bisnis_dan_informatika_kwik_kian_gie", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Internasional Semen Indonesia", valueDropdown: "universitas_internasional_semen_indonesia", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Negeri Madiun", valueDropdown: "politeknik_negeri_madiun", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Kristen Petra", valueDropdown: "universitas_kristen_petra", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Muhammadiyah Magelang", valueDropdown: "universitas_muhammadiyah_magelang", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Surabaya", valueDropdown: "universitas_surabaya", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Katolik Indonesia Atma Jaya", valueDropdown: "universitas_katolik_indonesia_atma_jaya", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Ciputra Surabaya", valueDropdown: "universitas_ciputra_surabaya", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Katolik Widya Mandala Surabaya", valueDropdown: "universitas_katolik_widya_mandala_surabaya", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Kristen Duta Wacana", valueDropdown: "universitas_kristen_duta_wacana", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Manufaktur Negeri Bangka Belitung", valueDropdown: "politeknik_manufaktur_negeri_bangka_belitung", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Kristen Krida Wacana", valueDropdown: "universitas_kristen_krida_wacana", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Institut Agama Islam Negeri Salatiga", valueDropdown: "institut_agama_islam_negeri_salatiga", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Muhammadiyah Purworejo", valueDropdown: "universitas_muhammadiyah_purworejo", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Institut Teknologi dan Bisnis Kalbis", valueDropdown: "institut_teknologi_dan_bisnis_kalbis", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Mercu Buana Jakarta", valueDropdown: "universitas_mercu_buana_jakarta", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "UPN “Veteran” Jakarta", valueDropdown: "upn_veteran_jakarta", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Pertamina", valueDropdown: "universitas_pertamina", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Dr. Soetomo", valueDropdown: "universitas_dr_soetomo", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Bakrie", valueDropdown: "universitas_bakrie", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Bengkulu", valueDropdown: "universitas_bengkulu", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "UIN Walisongo Semarang", valueDropdown: "uin_walisongo_semarang", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Islam Sultan Agung Semarang", valueDropdown: "universitas_islam_sultan_agung_semarang", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "UIN Imam Bonjol Padang", valueDropdown: "uin_imam_bonjol_padang", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Institut Pesantren Mathali’ul Falah Pati", valueDropdown: "institut_pesantren_mathali_ul_falah_pati", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "UIN Sunan Gunung Djati Bandung", valueDropdown: "uin_sunan_gunung_djati_bandung", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "IAIN Pekalongan", valueDropdown: "iain_pekalongan", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "UIN Sultan Aji Muhammad Idris Samarinda", valueDropdown: "uin_sultan_aji_muhammad_idris_samarinda", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Politeknik Jambi", valueDropdown: "politeknik_jambi", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Universitas Trisakti", valueDropdown: "universitas_trisakti", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Biro Institut Teknologi dan Bisnis Yadika Pasuruan", valueDropdown: "biro_institut_teknologi_dan_bisnis_yadika_pasuruan", isActive: true,),
  BebrasBiro(bebrasBiroUniv: "Biro Universitas Widyagama Malang", valueDropdown: "biro_universitas_widyagama_malang", isActive: true,),
];
