// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi2_NjRM36csHNrmY-zI-zE6oqJNMROJQ',
    appId: '1:267749218027:web:76591e4102dc7deee950ae',
    messagingSenderId: '267749218027',
    projectId: 'toki-bebras-proto',
    authDomain: 'toki-bebras-proto.firebaseapp.com',
    storageBucket: 'toki-bebras-proto.appspot.com',
    measurementId: 'G-4L8S00H4J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDPT3Wv3QH6u_YUmTJeVb9K3tFA0ljkCQ',
    appId: '1:267749218027:android:d956ce75d6bb1f53e950ae',
    messagingSenderId: '267749218027',
    projectId: 'toki-bebras-proto',
    storageBucket: 'toki-bebras-proto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9XaYXY4NxSx_mVeu5kIdAt2PKsMyFCc',
    appId: '1:267749218027:ios:0c7007133dc191a3e950ae',
    messagingSenderId: '267749218027',
    projectId: 'toki-bebras-proto',
    storageBucket: 'toki-bebras-proto.appspot.com',
    androidClientId:
        '267749218027-bv1a6apeup45q7dsvomjtrva0orlan0t.apps.googleusercontent.com',
    iosClientId:
        '267749218027-tjsagvulerptdvjv7s3bn2u1k0nu01vn.apps.googleusercontent.com',
    iosBundleId: 'com.toki.bebrasPandai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB9XaYXY4NxSx_mVeu5kIdAt2PKsMyFCc',
    appId: '1:267749218027:ios:2a0c5fbcea7be5b3e950ae',
    messagingSenderId: '267749218027',
    projectId: 'toki-bebras-proto',
    storageBucket: 'toki-bebras-proto.appspot.com',
    androidClientId:
        '267749218027-bv1a6apeup45q7dsvomjtrva0orlan0t.apps.googleusercontent.com',
    iosClientId:
        '267749218027-fguc55iacdahe4pvjsadnvtbb3lo1kuq.apps.googleusercontent.com',
    iosBundleId: 'com.toki.bebrasPandai.RunnerTests',
  );
}
